import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import TopLoader from "@/component/TopLoader";
import { PopupProvider } from "@/context/PopupContext";
import Footer from "../component/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Afsar’s Quest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopLoader/>
        <PopupProvider>
        <Header/>
        {children}
        <Footer/>
        </PopupProvider>
      </body>
    </html>
  );
}
